/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CharacteristicReadDto } from '../../models/characteristic-read-dto';

export interface CharacteristicsIdGet$Params {
  id: string;
}

export function characteristicsIdGet(http: HttpClient, rootUrl: string, params: CharacteristicsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CharacteristicReadDto>> {
  const rb = new RequestBuilder(rootUrl, characteristicsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CharacteristicReadDto>;
    })
  );
}

characteristicsIdGet.PATH = '/Characteristics/{id}';
