# build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app
COPY ./ ./
RUN dotnet restore
RUN dotnet tool restore
RUN dotnet ef migrations script --idempotent --output Migrations/migrate.sql

# serve
FROM alpine/psql
WORKDIR /app
COPY --from=build /app/Migrations/migrate.sql .
