/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyNumberCharacteristicUpdateDto } from '../../models/company-number-characteristic-update-dto';

export interface CompanyNumberCharacteristicsIdPut$Params {
  id: string;
      body?: CompanyNumberCharacteristicUpdateDto
}

export function companyNumberCharacteristicsIdPut(http: HttpClient, rootUrl: string, params: CompanyNumberCharacteristicsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, companyNumberCharacteristicsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

companyNumberCharacteristicsIdPut.PATH = '/CompanyNumberCharacteristics/{id}';
