/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NumberCharacteristicCreateDto } from '../../models/number-characteristic-create-dto';
import { NumberCharacteristicReadDto } from '../../models/number-characteristic-read-dto';

export interface NumberCharacteristicsPost$Params {
      body?: NumberCharacteristicCreateDto
}

export function numberCharacteristicsPost(http: HttpClient, rootUrl: string, params?: NumberCharacteristicsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<NumberCharacteristicReadDto>> {
  const rb = new RequestBuilder(rootUrl, numberCharacteristicsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NumberCharacteristicReadDto>;
    })
  );
}

numberCharacteristicsPost.PATH = '/NumberCharacteristics';
