/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NumberCharacteristicReadDto } from '../../models/number-characteristic-read-dto';

export interface NumberCharacteristicsGet$Params {
}

export function numberCharacteristicsGet(http: HttpClient, rootUrl: string, params?: NumberCharacteristicsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NumberCharacteristicReadDto>>> {
  const rb = new RequestBuilder(rootUrl, numberCharacteristicsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NumberCharacteristicReadDto>>;
    })
  );
}

numberCharacteristicsGet.PATH = '/NumberCharacteristics';
