/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CharacteristicType } from '../models/characteristic-type';
export interface CharacteristicReadDto {
  associatedCompanyCharacteristicCount?: number;
  color?: string | null;
  id?: string;
  label?: string | null;
  type?: CharacteristicType;
}
