/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CharacteristicType } from '../models/characteristic-type';
export interface CharacteristicUpdateDto {
  color?: string | null;
  label?: string | null;
  type?: CharacteristicType;
}
