/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistoricFinancialCharacteristicReadDto } from '../models/historic-financial-characteristic-read-dto';
import { HistoricNumberCharacteristicReadDto } from '../models/historic-number-characteristic-read-dto';
import { NumberCharacteristicReadDto } from '../models/number-characteristic-read-dto';
import { TextCharacteristicReadDto } from '../models/text-characteristic-read-dto';
export interface CharacteristicsCollectionReadDto {
  historicFinancialCharacteristics: Array<HistoricFinancialCharacteristicReadDto>;
  historicNumberCharacteristics: Array<HistoricNumberCharacteristicReadDto>;
  numberCharacteristics: Array<NumberCharacteristicReadDto>;
  textCharacteristics: Array<TextCharacteristicReadDto>;
}
