/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CharacteristicUpdateDto {
  color?: string | null;
  icon?: string | null;
  label?: string | null;
}
