/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyDto {
    dividendCurrency: string;
    id?: number;
    name: string;
    nextReportingDate: string;
    reportingCurrency: string;
    reportingMultiplier?: number;
    shareCurrency: string;
    shareIsin: string;
    shareSymbol: string;
}
