/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyCharacteristicReadDto } from '../models/company-characteristic-read-dto';
export interface CompanyReadDto {
  companyCharacteristics?: Array<CompanyCharacteristicReadDto> | null;
  id?: string;
  logoUrl?: string | null;
  name?: string | null;
}
