/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistoricValueReadDto } from '../models/historic-value-read-dto';
export interface CompanyHistoricNumberCharacteristicReadDto {
  color: string;
  historicNumberCharacteristicId: string;
  id: string;
  label: string;
  unit?: string | null;
  values: Array<HistoricValueReadDto>;
}
