/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyChangeDto {
  dividendCurrency: string;
  name: string;
  nextDividendRecordingDate?: string | null;
  nextReportingDate?: string | null;
  reportingCurrency: string;
  reportingMultiplier?: number;
  shareCurrency: string;
  shareIsin: string;
  shareSymbol: string;
  story?: string | null;
}
