/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistoricValueReadDto } from '../models/historic-value-read-dto';
export interface CompanyHistoricNumberCharacteristicReadDto {
  color?: string | null;
  historicNumberCharacteristicId?: string;
  id?: string;
  label?: string | null;
  unit?: string | null;
  values?: Array<HistoricValueReadDto> | null;
}
