/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportingDto } from '../models/reporting-dto';
export interface CompanyDto {
    dividendCurrency: string;
    id: number;
    name: string;
    nextReportingDate?: string | null;
    reportingCurrency: string;
    reportingMultiplier?: number;
    reportings?: Array<ReportingDto> | null;
    shareCurrency: string;
    shareIsin: string;
    shareSymbol: string;
    story?: string | null;
}
