/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyTextCharacteristicReadDto {
  color: string;
  id: string;
  label: string;
  textCharacteristicId: string;
  value: string;
}
