/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CharacteristicType } from '../models/characteristic-type';
import { HistoricValueReadDto } from '../models/historic-value-read-dto';
export interface CompanyHistoricCharacteristicReadDto {
  color?: string | null;
  historicCharacteristicId?: string | null;
  id?: string;
  label?: string | null;
  type?: CharacteristicType;
  unit?: string | null;
  values?: Array<HistoricValueReadDto> | null;
}
