/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';
import { HistoricValueCreateDto } from '../models/historic-value-create-dto';
export interface CompanyHistoricCurrencyCharacteristicCreateDto {
  companyId: string;
  currency: Currency;
  historicCurrencyCharacteristicId: string;
  values: Array<HistoricValueCreateDto>;
}
