/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';
import { FinancialReportingInterval } from '../models/financial-reporting-interval';
import { LinkCreateDto } from '../models/link-create-dto';
import { Multiplier } from '../models/multiplier';
import { StockExchange } from '../models/stock-exchange';
export interface CompanyUpdateDto {
  comment?: string | null;
  financialReportingCurrency: Currency;
  financialReportingInterval: FinancialReportingInterval;
  financialReportingMultiplier: Multiplier;
  links: Array<LinkCreateDto>;
  logoUrl?: string | null;
  name: string;
  stockCode: string;
  stockExchange: StockExchange;
}
