/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';
import { HistoricValueReadDto } from '../models/historic-value-read-dto';
export interface CompanyHistoricFinancialCharacteristicReadDto {
  color?: string | null;
  currency?: Currency;
  historicFinancialCharacteristicId?: string;
  id?: string;
  label?: string | null;
  values?: Array<HistoricValueReadDto> | null;
}
