/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistoricValueCreateDto } from '../models/historic-value-create-dto';
export interface CompanyHistoricNumberCharacteristicCreateDto {
  companyId: string;
  historicNumberCharacteristicId: string;
  values: Array<HistoricValueCreateDto>;
}
