/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyHistoricFinancialCharacteristicReadDto } from '../models/company-historic-financial-characteristic-read-dto';
import { CompanyHistoricNumberCharacteristicReadDto } from '../models/company-historic-number-characteristic-read-dto';
import { CompanyNumberCharacteristicReadDto } from '../models/company-number-characteristic-read-dto';
import { CompanyTextCharacteristicReadDto } from '../models/company-text-characteristic-read-dto';
import { Currency } from '../models/currency';
import { FinancialReportingInterval } from '../models/financial-reporting-interval';
import { Multiplier } from '../models/multiplier';
import { StockExchange } from '../models/stock-exchange';
export interface CompanyReadDto {
  comment?: string | null;
  companyHistoricFinancialCharacteristics: Array<CompanyHistoricFinancialCharacteristicReadDto>;
  companyHistoricNumberCharacteristics: Array<CompanyHistoricNumberCharacteristicReadDto>;
  companyNumberCharacteristics: Array<CompanyNumberCharacteristicReadDto>;
  companyTextCharacteristics: Array<CompanyTextCharacteristicReadDto>;
  financialReportingCurrency: Currency;
  financialReportingInterval: FinancialReportingInterval;
  financialReportingMultiplier: Multiplier;
  financialReportingSourceUrls?: Array<string> | null;
  id: string;
  logoUrl?: string | null;
  name: string;
  stockCode: string;
  stockCurrency: Currency;
  stockExchange: StockExchange;
}
