/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyHistoricCurrencyCharacteristicReadDto } from '../models/company-historic-currency-characteristic-read-dto';
import { CompanyHistoricNumberCharacteristicReadDto } from '../models/company-historic-number-characteristic-read-dto';
import { CompanyNumberCharacteristicReadDto } from '../models/company-number-characteristic-read-dto';
import { CompanyTextCharacteristicReadDto } from '../models/company-text-characteristic-read-dto';
import { Currency } from '../models/currency';
import { FinancialReportingInterval } from '../models/financial-reporting-interval';
import { Multiplier } from '../models/multiplier';
import { StockExchange } from '../models/stock-exchange';
export interface CompanyReadDto {
  comments?: Array<string> | null;
  companyHistoricCurrencyCharacteristics?: Array<CompanyHistoricCurrencyCharacteristicReadDto> | null;
  companyHistoricNumberCharacteristics?: Array<CompanyHistoricNumberCharacteristicReadDto> | null;
  companyNumberCharacteristics?: Array<CompanyNumberCharacteristicReadDto> | null;
  companyTextCharacteristics?: Array<CompanyTextCharacteristicReadDto> | null;
  financialReportingCurrency?: Currency;
  financialReportingInterval?: FinancialReportingInterval;
  financialReportingMultiplier?: Multiplier;
  financialReportingSourceUrls?: Array<string> | null;
  id?: string;
  logoUrl?: string | null;
  name?: string | null;
  stockExchange?: StockExchange;
  stockExchangeCode?: string | null;
  stockExchangeCurrency?: Currency;
}
