/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyCharacteristicCreateDto {
  characteristicId?: string;
  companyId?: string;
  unit?: string | null;
  value?: number;
}
