/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistoricValueCreateDto } from '../models/historic-value-create-dto';
export interface CompanyHistoricCharacteristicCreateDto {
  companyId?: string;
  historicCharacteristicId?: string;
  unit?: string | null;
  values?: Array<HistoricValueCreateDto> | null;
}
