/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CharacteristicType } from '../models/characteristic-type';
export interface CompanyCharacteristicReadDto {
  characteristicId?: string | null;
  color?: string | null;
  id?: string;
  label?: string | null;
  type?: CharacteristicType;
  unit?: string | null;
  value?: number;
}
