/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Currency } from '../models/currency';
import { FinancialReportingInterval } from '../models/financial-reporting-interval';
import { Multiplier } from '../models/multiplier';
import { StockExchange } from '../models/stock-exchange';
export interface CompanyUpdateDto {
  comments: Array<string>;
  financialReportingCurrency: Currency;
  financialReportingInterval: FinancialReportingInterval;
  financialReportingMultiplier: Multiplier;
  financialReportingSourceUrls: Array<string>;
  logoUrl?: string | null;
  name: string;
  stockExchange: StockExchange;
  stockExchangeCode: string;
}
