/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyNumberCharacteristicReadDto {
  color: string;
  id: string;
  label: string;
  numberCharacteristicId: string;
  unit?: string | null;
  value: number;
}
