/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DividendDto } from '../models/dividend-dto';
import { ReportingDto } from '../models/reporting-dto';
import { SharePriceDto } from '../models/share-price-dto';
export interface CompanyDto {
  dividendCurrency: string;
  dividends?: Array<DividendDto> | null;
  id: number;
  name: string;
  nextDividendRecordingDate?: string | null;
  nextReportingDate?: string | null;
  reportingCurrency: string;
  reportingMultiplier?: number;
  reportings?: Array<ReportingDto> | null;
  shareCurrency: string;
  shareIsin: string;
  sharePrices?: Array<SharePriceDto> | null;
  shareSymbol: string;
  story?: string | null;
}
