/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyNumberCharacteristicCreateDto {
  companyId: string;
  numberCharacteristicId: string;
  value: number;
}
