/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DividendChangeDto {
  amountPerShare: number;
  exDividendDate: string;
  paymentDate: string;
  periodEnd: string;
  periodStart: string;
}
