/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DividendDto {
  amountPerShare: number;
  exDividendDate: string;
  id: number;
  paymentDate: string;
  periodEnd: string;
  periodStart: string;
}
