/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HistoricNumberCharacteristicReadDto {
  associatedCompanyCharacteristicCount: number;
  color: string;
  id: string;
  label: string;
  unit?: string | null;
}
