/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NumberCharacteristicCreateDto {
  color: string;
  label: string;
  unit?: string | null;
}
