/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportingDto {
    comment?: string | null;
    earnings?: number;
    earningsPerShare?: number;
    id: number;
    periodEnd: string;
    periodStart: string;
    revenue?: number;
    totalAssets?: number;
    totalLiabilities?: number;
}
