/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum StockExchange {
  Swx = 'SWX',
  Nyse = 'NYSE',
  Nasdaq = 'NASDAQ',
  Lon = 'LON',
  Etr = 'ETR'
}
