/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TextCharacteristicReadDto {
  associatedCompanyCharacteristicCount: number;
  color: string;
  id: string;
  label: string;
}
