/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SharePriceChangeDto } from '../../models/share-price-change-dto';
import { SharePriceDto } from '../../models/share-price-dto';

export interface ApiCompaniesCompanyIdSharepricesPost$Json$Params {
  companyId: number;
      body: SharePriceChangeDto
}

export function apiCompaniesCompanyIdSharepricesPost$Json(http: HttpClient, rootUrl: string, params: ApiCompaniesCompanyIdSharepricesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SharePriceDto>> {
  const rb = new RequestBuilder(rootUrl, apiCompaniesCompanyIdSharepricesPost$Json.PATH, 'post');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SharePriceDto>;
    })
  );
}

apiCompaniesCompanyIdSharepricesPost$Json.PATH = '/api/companies/{companyId}/shareprices';
