/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { CompaniesService } from './services/companies.service';
import { CompanyHistoricFinancialCharacteristicsService } from './services/company-historic-financial-characteristics.service';
import { CompanyHistoricNumberCharacteristicsService } from './services/company-historic-number-characteristics.service';
import { CompanyNumberCharacteristicsService } from './services/company-number-characteristics.service';
import { CompanyTextCharacteristicsService } from './services/company-text-characteristics.service';
import { HistoricFinancialCharacteristicsService } from './services/historic-financial-characteristics.service';
import { HistoricNumberCharacteristicsService } from './services/historic-number-characteristics.service';
import { NumberCharacteristicsService } from './services/number-characteristics.service';
import { TextCharacteristicsService } from './services/text-characteristics.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    CompaniesService,
    CompanyHistoricFinancialCharacteristicsService,
    CompanyHistoricNumberCharacteristicsService,
    CompanyNumberCharacteristicsService,
    CompanyTextCharacteristicsService,
    HistoricFinancialCharacteristicsService,
    HistoricNumberCharacteristicsService,
    NumberCharacteristicsService,
    TextCharacteristicsService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
