/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiCompaniesGet$Plain$Params } from './fn/companies/api-companies-get-plain';
export { apiCompaniesGet$Plain } from './fn/companies/api-companies-get-plain';
export type { ApiCompaniesGet$Json$Params } from './fn/companies/api-companies-get-json';
export { apiCompaniesGet$Json } from './fn/companies/api-companies-get-json';
export type { ApiCompaniesPost$Plain$Params } from './fn/companies/api-companies-post-plain';
export { apiCompaniesPost$Plain } from './fn/companies/api-companies-post-plain';
export type { ApiCompaniesPost$Json$Params } from './fn/companies/api-companies-post-json';
export { apiCompaniesPost$Json } from './fn/companies/api-companies-post-json';
export type { ApiCompaniesCompanyIdGet$Plain$Params } from './fn/companies/api-companies-company-id-get-plain';
export { apiCompaniesCompanyIdGet$Plain } from './fn/companies/api-companies-company-id-get-plain';
export type { ApiCompaniesCompanyIdGet$Json$Params } from './fn/companies/api-companies-company-id-get-json';
export { apiCompaniesCompanyIdGet$Json } from './fn/companies/api-companies-company-id-get-json';
export type { ApiCompaniesCompanyIdPut$Params } from './fn/companies/api-companies-company-id-put';
export { apiCompaniesCompanyIdPut } from './fn/companies/api-companies-company-id-put';
export type { ApiCompaniesCompanyIdDelete$Params } from './fn/companies/api-companies-company-id-delete';
export { apiCompaniesCompanyIdDelete } from './fn/companies/api-companies-company-id-delete';
export type { ApiCompaniesCompanyIdReportingsPost$Plain$Params } from './fn/reportings/api-companies-company-id-reportings-post-plain';
export { apiCompaniesCompanyIdReportingsPost$Plain } from './fn/reportings/api-companies-company-id-reportings-post-plain';
export type { ApiCompaniesCompanyIdReportingsPost$Json$Params } from './fn/reportings/api-companies-company-id-reportings-post-json';
export { apiCompaniesCompanyIdReportingsPost$Json } from './fn/reportings/api-companies-company-id-reportings-post-json';
export type { ApiCompaniesCompanyIdReportingsReportingIdPut$Params } from './fn/reportings/api-companies-company-id-reportings-reporting-id-put';
export { apiCompaniesCompanyIdReportingsReportingIdPut } from './fn/reportings/api-companies-company-id-reportings-reporting-id-put';
export type { ApiCompaniesCompanyIdReportingsReportingIdDelete$Params } from './fn/reportings/api-companies-company-id-reportings-reporting-id-delete';
export { apiCompaniesCompanyIdReportingsReportingIdDelete } from './fn/reportings/api-companies-company-id-reportings-reporting-id-delete';
