/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiCompaniesGet$Plain$Params } from './fn/companies/api-companies-get-plain';
export { apiCompaniesGet$Plain } from './fn/companies/api-companies-get-plain';
export type { ApiCompaniesGet$Json$Params } from './fn/companies/api-companies-get-json';
export { apiCompaniesGet$Json } from './fn/companies/api-companies-get-json';
export type { ApiCompaniesPost$Plain$Params } from './fn/companies/api-companies-post-plain';
export { apiCompaniesPost$Plain } from './fn/companies/api-companies-post-plain';
export type { ApiCompaniesPost$Json$Params } from './fn/companies/api-companies-post-json';
export { apiCompaniesPost$Json } from './fn/companies/api-companies-post-json';
export type { ApiCompaniesIdGet$Plain$Params } from './fn/companies/api-companies-id-get-plain';
export { apiCompaniesIdGet$Plain } from './fn/companies/api-companies-id-get-plain';
export type { ApiCompaniesIdGet$Json$Params } from './fn/companies/api-companies-id-get-json';
export { apiCompaniesIdGet$Json } from './fn/companies/api-companies-id-get-json';
export type { ApiCompaniesIdPut$Params } from './fn/companies/api-companies-id-put';
export { apiCompaniesIdPut } from './fn/companies/api-companies-id-put';
export type { ApiCompaniesIdDelete$Params } from './fn/companies/api-companies-id-delete';
export { apiCompaniesIdDelete } from './fn/companies/api-companies-id-delete';
