/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CompanyChangeDto } from './models/company-change-dto';
export type { CompanyDto } from './models/company-dto';
export type { DividendChangeDto } from './models/dividend-change-dto';
export type { DividendDto } from './models/dividend-dto';
export type { ReportingChangeDto } from './models/reporting-change-dto';
export type { ReportingDto } from './models/reporting-dto';
export type { SharePriceChangeDto } from './models/share-price-change-dto';
export type { SharePriceDto } from './models/share-price-dto';
