/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CompanyChangeDto } from './models/company-change-dto';
export type { CompanyDto } from './models/company-dto';
export type { ReportingChangeDto } from './models/reporting-change-dto';
export type { ReportingDto } from './models/reporting-dto';
