/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistoricFinancialCharacteristicReadDto } from '../../models/historic-financial-characteristic-read-dto';

export interface HistoricFinancialCharacteristicsIdGet$Params {
  id: string;
}

export function historicFinancialCharacteristicsIdGet(http: HttpClient, rootUrl: string, params: HistoricFinancialCharacteristicsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<HistoricFinancialCharacteristicReadDto>> {
  const rb = new RequestBuilder(rootUrl, historicFinancialCharacteristicsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HistoricFinancialCharacteristicReadDto>;
    })
  );
}

historicFinancialCharacteristicsIdGet.PATH = '/HistoricFinancialCharacteristics/{id}';
