/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistoricCharacteristicReadDto } from '../../models/historic-characteristic-read-dto';

export interface GetHistoricCharacteristics$Params {
}

export function getHistoricCharacteristics(http: HttpClient, rootUrl: string, params?: GetHistoricCharacteristics$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HistoricCharacteristicReadDto>>> {
  const rb = new RequestBuilder(rootUrl, getHistoricCharacteristics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HistoricCharacteristicReadDto>>;
    })
  );
}

getHistoricCharacteristics.PATH = '/HistoricCharacteristics';
