/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface ApiCompaniesCompanyIdReportingsReportingIdDelete$Params {
    companyId: number;
    reportingId: number;
}

export function apiCompaniesCompanyIdReportingsReportingIdDelete(
    http: HttpClient,
    rootUrl: string,
    params: ApiCompaniesCompanyIdReportingsReportingIdDelete$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
    const rb = new RequestBuilder(
        rootUrl,
        apiCompaniesCompanyIdReportingsReportingIdDelete.PATH,
        'delete',
    );
    if (params) {
        rb.path('companyId', params.companyId, {});
        rb.path('reportingId', params.reportingId, {});
    }

    return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => {
            return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
        }),
    );
}

apiCompaniesCompanyIdReportingsReportingIdDelete.PATH =
    '/api/companies/{companyId}/reportings/{reportingId}';
