/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportingChangeDto } from '../../models/reporting-change-dto';

export interface ApiCompaniesCompanyIdReportingsReportingIdPut$Params {
  companyId: number;
  reportingId: number;
      body: ReportingChangeDto
}

export function apiCompaniesCompanyIdReportingsReportingIdPut(http: HttpClient, rootUrl: string, params: ApiCompaniesCompanyIdReportingsReportingIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiCompaniesCompanyIdReportingsReportingIdPut.PATH, 'put');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.path('reportingId', params.reportingId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiCompaniesCompanyIdReportingsReportingIdPut.PATH = '/api/companies/{companyId}/reportings/{reportingId}';
