/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistoricNumberCharacteristicReadDto } from '../../models/historic-number-characteristic-read-dto';

export interface HistoricNumberCharacteristicsGet$Params {
}

export function historicNumberCharacteristicsGet(http: HttpClient, rootUrl: string, params?: HistoricNumberCharacteristicsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HistoricNumberCharacteristicReadDto>>> {
  const rb = new RequestBuilder(rootUrl, historicNumberCharacteristicsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HistoricNumberCharacteristicReadDto>>;
    })
  );
}

historicNumberCharacteristicsGet.PATH = '/HistoricNumberCharacteristics';
