/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyDto } from '../../models/company-dto';

export interface ApiCompaniesGet$Plain$Params {}

export function apiCompaniesGet$Plain(
    http: HttpClient,
    rootUrl: string,
    params?: ApiCompaniesGet$Plain$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<Array<CompanyDto>>> {
    const rb = new RequestBuilder(rootUrl, apiCompaniesGet$Plain.PATH, 'get');
    if (params) {
    }

    return http.request(rb.build({ responseType: 'text', accept: 'text/plain', context })).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => {
            return r as StrictHttpResponse<Array<CompanyDto>>;
        }),
    );
}

apiCompaniesGet$Plain.PATH = '/api/Companies';
