/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyDto } from '../../models/company-dto';

export interface ApiCompaniesCompanyIdGet$Plain$Params {
    companyId: number;
}

export function apiCompaniesCompanyIdGet$Plain(
    http: HttpClient,
    rootUrl: string,
    params: ApiCompaniesCompanyIdGet$Plain$Params,
    context?: HttpContext,
): Observable<StrictHttpResponse<CompanyDto>> {
    const rb = new RequestBuilder(rootUrl, apiCompaniesCompanyIdGet$Plain.PATH, 'get');
    if (params) {
        rb.path('companyId', params.companyId, {});
    }

    return http.request(rb.build({ responseType: 'text', accept: 'text/plain', context })).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => {
            return r as StrictHttpResponse<CompanyDto>;
        }),
    );
}

apiCompaniesCompanyIdGet$Plain.PATH = '/api/companies/{companyId}';
