/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyReadDto } from '../../models/company-read-dto';

export interface CompaniesGet$Params {
}

export function companiesGet(http: HttpClient, rootUrl: string, params?: CompaniesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CompanyReadDto>>> {
  const rb = new RequestBuilder(rootUrl, companiesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CompanyReadDto>>;
    })
  );
}

companiesGet.PATH = '/Companies';
