/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyCreateDto } from '../../models/company-create-dto';
import { CompanyReadDto } from '../../models/company-read-dto';

export interface PostCompany$Params {
      body?: CompanyCreateDto
}

export function postCompany(http: HttpClient, rootUrl: string, params?: PostCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyReadDto>> {
  const rb = new RequestBuilder(rootUrl, postCompany.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyReadDto>;
    })
  );
}

postCompany.PATH = '/Companies';
