/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistoricCurrencyCharacteristicUpdateDto } from '../../models/historic-currency-characteristic-update-dto';

export interface HistoricCurrencyCharacteristicsIdPut$Params {
  id: string;
      body?: HistoricCurrencyCharacteristicUpdateDto
}

export function historicCurrencyCharacteristicsIdPut(http: HttpClient, rootUrl: string, params: HistoricCurrencyCharacteristicsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, historicCurrencyCharacteristicsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

historicCurrencyCharacteristicsIdPut.PATH = '/HistoricCurrencyCharacteristics/{id}';
