/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistoricCurrencyCharacteristicReadDto } from '../../models/historic-currency-characteristic-read-dto';

export interface HistoricCurrencyCharacteristicsGet$Params {
}

export function historicCurrencyCharacteristicsGet(http: HttpClient, rootUrl: string, params?: HistoricCurrencyCharacteristicsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HistoricCurrencyCharacteristicReadDto>>> {
  const rb = new RequestBuilder(rootUrl, historicCurrencyCharacteristicsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HistoricCurrencyCharacteristicReadDto>>;
    })
  );
}

historicCurrencyCharacteristicsGet.PATH = '/HistoricCurrencyCharacteristics';
