/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HistoricCurrencyCharacteristicCreateDto } from '../../models/historic-currency-characteristic-create-dto';
import { HistoricCurrencyCharacteristicReadDto } from '../../models/historic-currency-characteristic-read-dto';

export interface HistoricCurrencyCharacteristicsPost$Params {
      body?: HistoricCurrencyCharacteristicCreateDto
}

export function historicCurrencyCharacteristicsPost(http: HttpClient, rootUrl: string, params?: HistoricCurrencyCharacteristicsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<HistoricCurrencyCharacteristicReadDto>> {
  const rb = new RequestBuilder(rootUrl, historicCurrencyCharacteristicsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HistoricCurrencyCharacteristicReadDto>;
    })
  );
}

historicCurrencyCharacteristicsPost.PATH = '/HistoricCurrencyCharacteristics';
