/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TextCharacteristicReadDto } from '../../models/text-characteristic-read-dto';

export interface TextCharacteristicsIdGet$Params {
  id: string;
}

export function textCharacteristicsIdGet(http: HttpClient, rootUrl: string, params: TextCharacteristicsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TextCharacteristicReadDto>> {
  const rb = new RequestBuilder(rootUrl, textCharacteristicsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TextCharacteristicReadDto>;
    })
  );
}

textCharacteristicsIdGet.PATH = '/TextCharacteristics/{id}';
