name: Publish container images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: build and publish container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short SHA
        shell: bash
        run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fit-database-migrate container image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile.Database-Migrate
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fit-database-migrate:${{ env.sha_short }}

      - name: Build and push fit-identity container image
        uses: docker/build-push-action@v6
        with:
          context: ./identity
          file: ./identity/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fit-identity:${{ env.sha_short }}

      - name: Build and push fit-backend container image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fit-backend:${{ env.sha_short }}

      - name: Build and push fit-frontend container image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fit-frontend:${{ env.sha_short }}
