name: Deploy to DigitalOcean droplet

on:
  workflow_run:
    workflows: ["Publish container images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        shell: bash
        run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Create .env
        run: |
          echo "FIT_DATABASE_PASSWORD=${{ secrets.FIT_DATABASE_PASSWORD }}" > .env
          echo "IMAGE_TAG=${{ env.sha_short }}" > .env

      - name: Copy .env and compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env,compose.yml"
          target: "/app"

      - name: Docker compose down and up
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "cd /app && docker compose down --remove-orphans && docker compose up --detach --force-recreate --no-build"
