/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DividendChangeDto } from '../../models/dividend-change-dto';

export interface ApiCompaniesCompanyIdDividendsDividendIdPut$Params {
  companyId: number;
  dividendId: number;
      body: DividendChangeDto
}

export function apiCompaniesCompanyIdDividendsDividendIdPut(http: HttpClient, rootUrl: string, params: ApiCompaniesCompanyIdDividendsDividendIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiCompaniesCompanyIdDividendsDividendIdPut.PATH, 'put');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.path('dividendId', params.dividendId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiCompaniesCompanyIdDividendsDividendIdPut.PATH = '/api/companies/{companyId}/dividends/{dividendId}';
