/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiCompaniesCompanyIdDividendsDividendIdDelete$Params {
  companyId: number;
  dividendId: number;
}

export function apiCompaniesCompanyIdDividendsDividendIdDelete(http: HttpClient, rootUrl: string, params: ApiCompaniesCompanyIdDividendsDividendIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiCompaniesCompanyIdDividendsDividendIdDelete.PATH, 'delete');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.path('dividendId', params.dividendId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiCompaniesCompanyIdDividendsDividendIdDelete.PATH = '/api/companies/{companyId}/dividends/{dividendId}';
